Darwin
-------
image:https://travis-ci.org/darwin-evolution/darwin.svg[alt="Travis"]
image:https://img.shields.io/badge/license-MIT-brightgreen.svg[alt="MIT License"]

== Why?
Darwin was creataed to ease refactoring. He allows You to test Your new
implementation, in any environment, even in production (that of course needs some care and caution).
Darwin basically executes existing and new implementations (in sequence) comparing results, logging
the outcome and returning value from choosen implementation.

== How?

=== Coding

Darwin has very little dependencies:

* http://www.slf4j.org/[slf4j]
* https://github.com/typesafehub/config[typesafe-config]
* http://metrics.dropwizard.io/3.1.0/[dropwizard-metrics]

that's all he needs to help Your code Evolve!

=== Evolving

Basic idea in darwin is evolution, it is transition from **'protoplast'** to **'evolved'**
implementation. This process is monitored and logged, increasing safety
of your refactorings, and providing an easy way to test backward compatibility,
because by default it returns.


==== So evolve!

Given two implementations: calculateMax and calculateMaxWithMath
we can write a simple evolution:

.Sample evolution
[source,java]
----
        final Integer a = 1, b = 3, c = -1; // <1>

        Integer max = Evolution.<Integer>of("calculateMax") // <2>
                .from(new ProtoplastExecutionHarness<Integer>() { // <3>
                    @Override
                    public Integer execute() throws Exception {
                        arguments(a, b, c); // <4>
                        return calculateMax(a, b, c); // <5>
                    }
                })
                .to(new EvolvedExecutionHarness<Integer>() { // <6>
                    @Override
                    public Integer execute() throws Exception {
                        arguments(a, b, c); // <7>
                        return calculateMax2(a, b, c); // <8>
                    }
                })
                .evolve(); // <9>
----
<1> Define arguments
<2> Create Evolution named "calculateMax"
<3> Create Protoplast execution harness - it will hold our old implementation
<4> We log protoplast arguments
<5> We execute protoplast implementation
<6> Create Evolved executution harness - it will hold our new implementation
<7> We log evolved arguments
<8> we execute evolved implementation
<9> And we return configured result either (protoplast or evolved)

Such configuration will result in slf4j log message (<<anchor-1,Layout explained here>>) in **trace** level in category **darwin.evolution**:

[source,csv]
----
       "calculateMax"|"PROTOPLAST"|"1463682597919"|"OK"||"249896"||||"171597"|||
----


==== Choosing implementation

Darwin works out of the box by returning **'protoplast'** implementation's result.
To choose which implementation's result should be returned to caller, Darwin uses
ImplementationChooser. By default it uses Typesafe Config, to lookup which
implementation is preferred.

.ImplementationChooser listing (https://github.com/darwin-evolution/darwin/blob/master/darwin/src/main/java/com/github/darwinevolution/darwin/api/ImplementationChooser.java[source])
[source,java]
----
        public abstract class ImplementationChooser {

            public abstract ImplementationPreference chooseImplementation(String evolutionName);
        ...
        }
----

So to control which result should be returned you can either write your own implementation, or configure default.
To return **evolved** implementation's result default chooser looks for configuration variable according to scheme:

[source,java]
----
       darwin.evolution.<evolutionName>.evolved = true
----

Simplest way to provide it, is via system properties:

[source,java]
----
    -Ddarwin.evolution.calculateMax.evolved=true // evolved implementation result will be returned
    -Ddarwin.evolution.calculateMax.evolved=false // protoplast implementation result will be returned
----

or if you want to unleash full power of typesafe config go visit https://github.com/typesafehub/config[it's homepage.]

=== Maven

Base dependency:

[source,xml]
----
<dependency>
    <groupId>com.github.darwin-evolution</groupId>
    <artifactId>darwin</artifactId>
    <version>0.9.1</version>
</dependency>
----

=== Logging in JSON format

To log evolution information in JSON format we need to add extra dependency:


[source,xml]
----
<dependency>
    <groupId>com.github.darwin-evolution</groupId>
    <artifactId>darwin-jackson</artifactId>
    <version>0.9.1</version>
</dependency>
----

We're using jackson because it is most popular JSON serializer for JavaEE projects.
Sample json output, that will be logged to slf4j (TRACE, darwin.evolution):

[source,json]
----
{
	"name": "testEvolution",
	"implementationPreference": "EVOLVED",
	"timestamp": 1465313830367,
	"resultType": "OK",
	"protoplastDurationNs": 100,
	"protoplastArguments": [1, 2],
	"protoplastValue": "6",
	"protplastException": null,
	"evolvedDurationNs": 130,
	"evolvedArguments": [1, 2],
	"evolvedValue": "6",
	"evolvedException": null
}
----

=== Default result logging layout [[anchor-1]]

By default, results are logged in psv (pipe separated values) format, to slf4j.
It logs in **TRACE** level under category: **darwin.evolution**.
Format is following:


.PSV layout
----

"evolution name"|"chosen implementation"|"execution timestamp"|"result code"|"[protopast arguments]"|"protoplast duration"|"protoplast exception"|"protoplast value"|"[evovled arguments]"|"evolved duration"|"evolved exception"|"evolved value"|

----

.Description
* evolution name - name of the evolution as provided
* choosen implementation - which implementation's result was returned
** **PROTOPLAST** - for protoplast impelementation's result
** **EVOLVED** - for evolved implementation's result
* execution timestamp - java timestamp of begining of execution
* result code - code denoting result of comparison (com.github.darwinevolution.darwin.execution.result.ResultType)
** **OK** - if both implementations returned values, and values match according to provided **ValueResultComparator**
** **OK_EXCEPTIONS** - if both implementations thrown exceptions, and those exceptions match according to provided **ExceptionResultComparator**
** **ERROR_DIFFERENT_EXCEPTIONS** - if both implementations thrown exceptions, and those exceptions do not match according to provided **ExceptionResultComparator**
** **ERROR_DIFFERENT_RESULTS** - if both implementations returned values, and values do not match according to provided **ValueResultComparator**
** **ERROR_EXCEPTION_VS_RESULT** - if either impelementation returned value, and the other one thrown exception
* protoplast arguments - conatins list of arguments provided to protoplast implementation
* protoplast duration - duration of protoplast execution in ns
* protoplast exception - message from exception thrown by protoplast implementation
* protoplast value - **String.valueOf** from value retunred by protoplast implementation
* evolved arguments - conatins list of arguments provided to evolved implementation
* evolved duration - duration of evolved execution in ns
* evolved exception - message from exception thrown by evolved implementation
* evolved value - **String.valueOf** from value retunred by evolved implementation

Values effectively logged depend on provided configuration in https://github.com/darwin-evolution/darwin/blob/master/darwin/src/main/java/com/github/darwinevolution/darwin/api/ResultConsumerConfiguration.java[ResultConsumerConfiguration].
Default behavoiur is:

* if result is from OK_ family message will contain:
** evolution name
** choosen implementation
** execution timestamp
** result code
** protoplast duration
** evolved duration
* if result is from ERROR family it will contain all fields



.Sample log messages
[source,java]
----
       "calculateMax"|"PROTOPLAST"|"1465408345511"|"OK"||"93591"||||"72753"||| //valid result
       "calculateMax"|"PROTOPLAST"|"1465408345593"|"ERROR_DIFFERENT_RESULTS"|"[1,3,-1]"|"9352"|"3"||"[1,3,-1]"|"11835"|"2"|| //error result

----



=== Examples

More examples can be found https://github.com/darwin-evolution/darwin/blob/master/darwin/src/test/java/com/github/darwinevolution/darwin/EvolutionTest.java[here.]
